apiVersion: v1
kind: Pod
metadata:
  name: multi-Ccntainer-shared-volume
  labels:
    name: mc
spec:
  containers:
  - name: webserver
    image: nginx
    resources:
      limits:
        memory: "500Mi"             # 500 MiB of RAM
        cpu: "500m"                # This means 0.5 vCPU
    volumeMounts:
    - name: webserver
      mountPath: /usr/share/nginx/html


  volumes:
  - name: webserver
    emptyDir: {}


