apiVersion: v1
kind: PersistentVolume
metadata:
  name: myPV
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  nfs:
    server: "<server IP>"
    path: "/dataDirectory"