apiVersion: v1
kind: Pod
metadata:
  name: multi-Ccntainer-shared-volume
  labels:
    name: mc
spec:
  containers:
  - name: webserver
    image: nginx
    resources:
      limits:
        memory: "500Mi"             # 500 MiB of RAM
        cpu: "500m"                # This means 0.5 vCPU
    volumeMounts:
    - name: webserver
      mountPath: /usr/share/nginx/html # In this Path Nginx Generates Log

  - name: debian
    image: debian
    resources:
      limits:
        memory: "500Mi"             # 500 MiB of RAM
        cpu: "500m"   
    volumeMounts:
    - name: webserver
      mountPath: /html
    
  volumes:                  # Creating a volume to be shared between the Multiple Containers in a single POD.
  - name: webserver
    emptyDir: {}


