apiVersion: v1
kind: POD
metadata:
  name: ipcpod
spec:
  containers:
  - name: container1
    image: allingeek/ch6_ipc
    command: ["./ipc", "-producer"]

  - name: container2
    image: allingeek/ch6_ipc
    command: ["./ipc", "-consumer"]
